# what do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage # to bind with persistent volume
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage # to bind with persistent volume claim
  accessMode:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/mnt/somenew/directory/structure/"
    type: DirectoryOrCreate
